#pragma once

#include "structs.h"

extern int minMapVisY;
extern int maxMapVisY;
extern int minFontSize;
extern int maxFontSize;
extern short mapVisY;
extern short mapVisX;
extern short windowX;
extern short windowY;
extern short borderDelimiter;
extern short fontSize;
extern int invSize;
extern int startSkill;
extern int startSkillRandom;
extern int startHp;
extern int heroStartVisDistance;
extern int raceCount;
const int human = 0;
const int dwarf = 1;
const int elf = 2;
extern short scrollDist;
const int maxLevel = 10;
extern int XP_table[maxLevel];
extern int characteristicsNumber;
const int strength = 0;
const int dexterity = 1;
const int intelligence = 2;
extern int newLevelPoints;
const int logSize = 16;
const int logoSize = 5;
const int historySize = 24;
extern int copyrightSize;
extern int keyLength;
extern short Black;
extern short Blue;
extern short Green;
extern short Cyan;
extern short Red;
extern short Magenta;
extern short Brown;
extern short LightGray;
extern short DarkGray;
extern short LightBlue;
extern short LightGreen;
extern short LightCyan;
extern short LightRed;
extern short LightMagenta;
extern short Yellow;
extern short White;
const int NPCTypesNum = 10;
extern int rat;
extern int vepr;
extern int wolf;
extern int goblin;
extern int gnoll;
extern int bear;
extern int Ork;
extern int Troll;
extern int Werewolf;
extern int Ogr;
extern TTile NPC_tiles[NPCTypesNum];
extern TNPC NPC_types[NPCTypesNum];
const int tilesNum = 19;
extern int grassD;
extern int grassL;
extern int grassB;
extern int sandD;
extern int sandL;
extern int sandB;
extern int trapGrassD;
extern int trapGrassL;
extern int trapGrassB;
extern int trapKnown;
extern int trapUsed;
extern int waterL;
extern int treeD;
extern int treeL;
extern int treeB;
extern int rockD;
extern int rockL;
extern int rockW;
extern int waterD;
extern int minTrap;
extern float trapHPpc;
extern float trapDisarmpc;
extern TTile Tiles[tilesNum];
const int itemsNum = 20;
const int blank = -1;
const int weapon = 0;
const int armor = 1;
const int poultice = 2;
extern TItem Items[itemsNum];
const int poulticeNum = 3;
extern TItem poultices[poulticeNum];
extern TItem blankItem;
extern int spawnArea;
