#pragma once

#include <string>

using namespace std;

static wstring sCoordinates = L"Координаты";
static wstring sHP = L"Здоровье  ";
static wstring sXP = L"Опыт      ";
static wstring sStrength = L"Сила     ";
static wstring sDexterity = L"Ловкость ";
static wstring sIntelligence = L"Интеллект";
static wstring sLevel = L"Уровень   ";
static wstring sMonsters[2] = { L"Л. мышь", L"Гоблин" };
static wstring sCWeapon = L"Оружие : ";
static wstring sCArmor = L"Броня  : ";
static wstring sIncExp1 = L"Получено ";
static wstring sIncExp2 = L" опыта";
static wstring sNewLevel = L"Новый уровень!";
static wstring sDamageToEnemy = L"Нанесен урон ";
static wstring sDamageToHero1 = L" нанес ";
static wstring sDamageToHero2 = L" урона";
static wstring sKilling = L" убит!";
static wstring sDodged = L" увернулся!";
static wstring sHeroDodged = L"Вы увернулись от ";
static wstring sNoDamage = L" не пробил защиту";
static wstring sReceived = L"Получено ";
static wstring sItems[6] = { L"Железный меч", L"Копье", L"Стальной меч", L"Кожанная броня", L"Кольчуга", L"Латные доспехи" };
static wstring sMotion = L"Движение";
static wstring sAttack = L"Атака";
static wstring sInventory = L"Инвентарь";
static wstring sCharacteristics = L"Характеристики";
static wstring sDodgeСhance = L"Шанс увернуться";
static wstring sMenu = L"Меню";
static wstring sInfo = L"Информация";
static wstring sHints = L"Управление";
static wstring sSelect = L"Выбор";
static wstring sUse = L"Использовать";
static wstring sDelete = L"Выкинуть";
static wstring sBack = L"Назад";
static wstring sDamage = L"Урон  ";
static wstring sDefense = L"Защита";
static wstring sMaxHP = L"Максимальное здоровье";
static wstring sPoints = L"Очки";
static wstring sAccept = L"Принять";
static wstring sClear = L"Очистить";
static wstring sIncrease = L"Увеличить";
static wstring sDecrease = L"Уменьшить";
static wstring sMulExp = L"Множитель опыта";
static wstring sSkip = L"Пропуск хода";
static wstring sDeath = L"Вы убиты!";

static wstring sDelimeter = L": ";
static wstring sSlash = L" / ";
static wstring sComma = L", ";
static wstring sSpace = L" ";
static wstring sAsterisk = L"*";
static wstring sPercent = L"%";
static wstring sRadio = L"( ) ";
static wstring sLack = L"---";
static wstring sWindowName = L"Valden";
static wstring skArrows = L"arrows";
static wstring skWASD = L"wasd";
static wstring skI = L"i";
static wstring skC = L"c";
static wstring skEsc = L"Esc";
static wstring skPlus = L"+";
static wstring skMinus = L"-";
static wstring skEnter = L"Enter";
static wstring skSpace = L"Space";
static wstring skTab = L"Tab";
